ocamltest: compute ocamlsrcdir during configure rather than during build

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -820,6 +820,7 @@ outputobj
 outputexe
 ocamlyacc_wstr_module
 unix_or_win32
+ocamlsrcdir
 systhread_support
 system
 model
@@ -2923,6 +2924,7 @@ OCAML_VERSION_SHORT=5.0
 
 
 
+
  # TODO: rename this variable
 
 
@@ -2968,6 +2970,8 @@ ac_config_files="$ac_config_files stdlib/sys.ml"
 ac_config_files="$ac_config_files manual/src/version.tex"
 
 ac_config_files="$ac_config_files manual/src/html_processing/src/common.ml"
+
+ac_config_files="$ac_config_files ocamltest/ocamltest_config.mlp"
 
 ac_config_files="$ac_config_files tools/eventlog_metadata"
 
@@ -12653,16 +12657,27 @@ case $ocaml_cv_cc_vendor in #(
   CPP="$CC -E -P" ;;
 esac
 
+# Absolute path to the toplevel source directory
+
+# A sentinelle character (X) is added ad the end of the directory name
+# and then removed, in case it finishes with an odd character.
+
+ocamlsrcdir=$(unset CDPATH; cd -- "$srcdir" && printf %sX "$PWD") || fail
+ocamlsrcdir=${ocamlsrcdir%X}
+
 # Libraries to build depending on the host
 
 case $host in #(
   *-*-mingw32|*-pc-windows) :
     unix_or_win32="win32"
-    ocamlyacc_wstr_module="yacc/wstr" ;; #(
+    ocamlyacc_wstr_module="yacc/wstr"
+    ocamlsrcdir=`echo "$ocamlsrcdir" | cygpath -w -f - \
+      | sed -e 's%\\\\%\\\\\\\\%g'` ;; #(
   *) :
     unix_or_win32="unix"
   ocamlyacc_wstr_module="" ;;
 esac
+
 case $host in #(
   *-*-cygwin*|*-*-mingw32|*-pc-windows) :
     exeext=".exe" ;; #(
@@ -19129,6 +19144,7 @@ do
     "stdlib/sys.ml") CONFIG_FILES="$CONFIG_FILES stdlib/sys.ml" ;;
     "manual/src/version.tex") CONFIG_FILES="$CONFIG_FILES manual/src/version.tex" ;;
     "manual/src/html_processing/src/common.ml") CONFIG_FILES="$CONFIG_FILES manual/src/html_processing/src/common.ml" ;;
+    "ocamltest/ocamltest_config.mlp") CONFIG_FILES="$CONFIG_FILES ocamltest/ocamltest_config.mlp" ;;
     "tools/eventlog_metadata") CONFIG_FILES="$CONFIG_FILES tools/eventlog_metadata" ;;
     "runtime/caml/m.h") CONFIG_HEADERS="$CONFIG_HEADERS runtime/caml/m.h" ;;
     "runtime/caml/s.h") CONFIG_HEADERS="$CONFIG_HEADERS runtime/caml/s.h" ;;
